/**
 * Generated by Verge3D Puzzles v.3.6.1
 * Mon Jan 24 2022 10:48:06 GMT+0100 (heure normale d’Europe centrale)
 * Prefer not editing this file as your changes may get overridden once Puzzles are saved.
 * Check out https://www.soft8soft.com/docs/manual/en/introduction/Using-JavaScript.html
 * for the information on how to add your own JavaScript to Verge3D apps.
 */

'use strict';

(function() {

// global variables/constants used by puzzles' functions

var LIST_NONE = '<none>';

var _pGlob = {};

_pGlob.objCache = {};
_pGlob.fadeAnnotations = true;
_pGlob.objClickInfo = [];
_pGlob.pickedObject = '';
_pGlob.objHoverInfo = [];
_pGlob.hoveredObject = '';
_pGlob.objMovementInfos = {};
_pGlob.objDragOverCallbacks = [];
_pGlob.objDragOverInfoByBlock = {}
_pGlob.dragMoveOrigins = {};
_pGlob.dragScaleOrigins = {};
_pGlob.mediaElements = {};
_pGlob.loadedFiles = {};
_pGlob.loadedFile = '';
_pGlob.promiseValue = '';
_pGlob.animMixerCallbacks = [];
_pGlob.arHitPoint = new v3d.Vector3(0, 0, 0);
_pGlob.states = [];
_pGlob.percentage = 0;
_pGlob.animateParamUpdate = null;
_pGlob.openedFile = '';
_pGlob.xrSessionAcquired = false;
_pGlob.xrSessionCallbacks = [];
_pGlob.screenCoords = new v3d.Vector2();
_pGlob.gamepadIndex = 0;

_pGlob.AXIS_X = new v3d.Vector3(1, 0, 0);
_pGlob.AXIS_Y = new v3d.Vector3(0, 1, 0);
_pGlob.AXIS_Z = new v3d.Vector3(0, 0, 1);
_pGlob.MIN_DRAG_SCALE = 10e-4;
_pGlob.SET_OBJ_ROT_EPS = 1e-8;

_pGlob.vec2Tmp = new v3d.Vector2();
_pGlob.vec2Tmp2 = new v3d.Vector2();
_pGlob.vec3Tmp = new v3d.Vector3();
_pGlob.vec3Tmp2 = new v3d.Vector3();
_pGlob.vec3Tmp3 = new v3d.Vector3();
_pGlob.vec3Tmp4 = new v3d.Vector3();
_pGlob.eulerTmp = new v3d.Euler();
_pGlob.eulerTmp2 = new v3d.Euler();
_pGlob.quatTmp = new v3d.Quaternion();
_pGlob.quatTmp2 = new v3d.Quaternion();
_pGlob.colorTmp = new v3d.Color();
_pGlob.mat4Tmp = new v3d.Matrix4();
_pGlob.planeTmp = new v3d.Plane();
_pGlob.raycasterTmp = new v3d.Raycaster();
_pGlob.intervals = {};

var _pPhysics = {};

_pPhysics.tickCallbacks = [];
_pPhysics.syncList = [];
_pPhysics.consList = [];

// internal info
_pPhysics.collisionData = [];

// goes to collision callback
_pPhysics.collisionInfo = {
    objectA: '',
    objectB: '',
    distance: 0,
    positionOnA: [0, 0, 0],
    positionOnB: [0, 0, 0],
    normalOnB: [0, 0, 0]
};

var _noWebAudioReported = false;
var _webAudioTinySynth = null;

var PL = v3d.PL = v3d.PL || {};

// a more readable alias for PL (stands for "Puzzle Logic")
v3d.puzzles = PL;

PL.procedures = PL.procedures || {};



PL.execInitPuzzles = function(options) {
    // always null, should not be available in "init" puzzles
    var appInstance = null;
    // app is more conventional than appInstance (used in exec script and app templates)
    var app = null;

    var _initGlob = {};
    _initGlob.percentage = 0;
    _initGlob.output = {
        initOptions: {
            fadeAnnotations: true,
            useBkgTransp: false,
            preserveDrawBuf: false,
            useCompAssets: false,
            useFullscreen: true,
            useCustomPreloader: false,
            preloaderStartCb: function() {},
            preloaderProgressCb: function() {},
            preloaderEndCb: function() {},
        }
    }

    // provide the container's id to puzzles that need access to the container
    _initGlob.container = options !== undefined && 'container' in options
            ? options.container : "";

    

    var PROC = {
    
};


// utility functions envoked by the HTML puzzles
function getElements(ids, isParent) {
    var elems = [];
    if (Array.isArray(ids) && ids[0] != 'CONTAINER' && ids[0] != 'WINDOW' &&
        ids[0] != 'DOCUMENT' && ids[0] != 'BODY' && ids[0] != 'QUERYSELECTOR') {
        for (var i = 0; i < ids.length; i++)
            elems.push(getElement(ids[i], isParent));
    } else {
        elems.push(getElement(ids, isParent));
    }
    return elems;
}

function getElement(id, isParent) {
    var elem;
    if (Array.isArray(id) && id[0] == 'CONTAINER') {
        if (appInstance !== null) {
            elem = appInstance.container;
        } else if (typeof _initGlob !== 'undefined') {
            // if we are on the initialization stage, we still can have access
            // to the container element
            var id = _initGlob.container;
            if (isParent) {
                elem = parent.document.getElementById(id);
            } else {
                elem = document.getElementById(id);
            }
        }
    } else if (Array.isArray(id) && id[0] == 'WINDOW') {
        if (isParent)
            elem = parent;
        else
            elem = window;
    } else if (Array.isArray(id) && id[0] == 'DOCUMENT') {
        if (isParent)
            elem = parent.document;
        else
            elem = document;
    } else if (Array.isArray(id) && id[0] == 'BODY') {
        if (isParent)
            elem = parent.document.body;
        else
            elem = document.body;
    } else if (Array.isArray(id) && id[0] == 'QUERYSELECTOR') {
        if (isParent)
            elem = parent.document.querySelector(id);
        else
            elem = document.querySelector(id);
    } else {
        if (isParent)
            elem = parent.document.getElementById(id);
        else
            elem = document.getElementById(id);
    }
    return elem;
}



// setHTMLElemStyle puzzle
function setHTMLElemStyle(prop, value, ids, isParent) {
    var elems = getElements(ids, isParent);
    for (var i = 0; i < elems.length; i++) {
        var elem = elems[i];
        if (!elem || !elem.style)
            continue;
        elem.style[prop] = value;
    }
}



// setHTMLElemAttribute puzzle
function setHTMLElemAttribute(attr, value, ids, isParent) {
    var elems = getElements(ids, isParent);
    for (var i = 0; i < elems.length; i++) {
        var elem = elems[i];
        if (!elem) continue;

        if (attr === 'style') {
            // NOTE: setting an attribute 'style' instead of a property 'style'
            // fixes IE11 worng behavior
            elem.setAttribute(attr, value);
        } else {
            elem[attr] = value;
        }
    }
}




// initPreloader puzzle
_initGlob.output.initOptions.useCustomPreloader = true;
_initGlob.output.initOptions.preloaderStartCb = function() {
    _initGlob.percentage = 0;
    (function() {})();
};
_initGlob.output.initOptions.preloaderProgressCb = function(percentage) {
    _initGlob.percentage = percentage;
    (function() {
  setHTMLElemStyle('width', String(Math.round(_initGlob.percentage)) + '%', 'progress_bar', false);
  setHTMLElemAttribute('innerHTML', String(Math.round(_initGlob.percentage)) + '%', 'percentage', false);
})();
};
_initGlob.output.initOptions.preloaderEndCb = function() {
    _initGlob.percentage = 100;
    (function() {
  setHTMLElemStyle('display', 'none', 'preloader_div', false);
  setHTMLElemStyle('visibility', 'visible', ['boutonmenu', 'boutonmenu_return'], true);
  setHTMLElemStyle('visibility', 'visible', 'Title0', true);
  setHTMLElemStyle('visibility', 'hidden', ['picocon1', 'picocon2', 'picocon3', 'picocon4', 'picocon5', 'picocon6', 'picocon7', 'picocon8', 'picocon9', 'picocon10', 'picocon11', 'picocon12', 'picocon13', 'picocon14', 'picocon15'], true);
})();
};

    return _initGlob.output;
}

PL.init = function(appInstance, initOptions) {

// app is more conventional than appInstance (used in exec script and app templates)
var app = appInstance;

initOptions = initOptions || {};

if ('fadeAnnotations' in initOptions) {
    _pGlob.fadeAnnotations = initOptions.fadeAnnotations;
}

this.procedures["Reboot"] = Reboot;
this.procedures["Unmount"] = Unmount;
this.procedures["Unincline"] = Unincline;
this.procedures["OpenAR"] = OpenAR;
this.procedures["CloseAR"] = CloseAR;
this.procedures["shadeBodyOn"] = shadeBodyOn;
this.procedures["Setpad1"] = Setpad1;
this.procedures["SetMount1"] = SetMount1;
this.procedures["SetTilt1"] = SetTilt1;
this.procedures["shadeBodyOff"] = shadeBodyOff;
this.procedures["PerformPad1"] = PerformPad1;
this.procedures["PerformTilt1"] = PerformTilt1;
this.procedures["PerformMount1"] = PerformMount1;
this.procedures["SetPad2"] = SetPad2;
this.procedures["SetMount2"] = SetMount2;
this.procedures["SetTilt2"] = SetTilt2;
this.procedures["PerformPad2"] = PerformPad2;
this.procedures["PerformTilt2"] = PerformTilt2;
this.procedures["PerformMount2"] = PerformMount2;
this.procedures["SetPad3"] = SetPad3;
this.procedures["SetMount3"] = SetMount3;
this.procedures["SetTilt3"] = SetTilt3;
this.procedures["PerformPad3"] = PerformPad3;
this.procedures["PerformTilt3"] = PerformTilt3;
this.procedures["PerformMount3"] = PerformMount3;
this.procedures["SetPad4"] = SetPad4;
this.procedures["SetTilt4"] = SetTilt4;
this.procedures["PerformPad4"] = PerformPad4;
this.procedures["PerformTilt4"] = PerformTilt4;
this.procedures["SetPad5"] = SetPad5;
this.procedures["PerformPad5"] = PerformPad5;
this.procedures["ShowPic1"] = ShowPic1;
this.procedures["Terminate"] = Terminate;
this.procedures["ShowPic2"] = ShowPic2;
this.procedures["ShowPic3"] = ShowPic3;
this.procedures["ShowPic4"] = ShowPic4;
this.procedures["ShowPic5"] = ShowPic5;
this.procedures["ShowPic6"] = ShowPic6;
this.procedures["ShowPic7"] = ShowPic7;

var PROC = {
    "Reboot": Reboot,
    "Unmount": Unmount,
    "Unincline": Unincline,
    "OpenAR": OpenAR,
    "CloseAR": CloseAR,
    "shadeBodyOn": shadeBodyOn,
    "Setpad1": Setpad1,
    "SetMount1": SetMount1,
    "SetTilt1": SetTilt1,
    "shadeBodyOff": shadeBodyOff,
    "PerformPad1": PerformPad1,
    "PerformTilt1": PerformTilt1,
    "PerformMount1": PerformMount1,
    "SetPad2": SetPad2,
    "SetMount2": SetMount2,
    "SetTilt2": SetTilt2,
    "PerformPad2": PerformPad2,
    "PerformTilt2": PerformTilt2,
    "PerformMount2": PerformMount2,
    "SetPad3": SetPad3,
    "SetMount3": SetMount3,
    "SetTilt3": SetTilt3,
    "PerformPad3": PerformPad3,
    "PerformTilt3": PerformTilt3,
    "PerformMount3": PerformMount3,
    "SetPad4": SetPad4,
    "SetTilt4": SetTilt4,
    "PerformPad4": PerformPad4,
    "PerformTilt4": PerformTilt4,
    "SetPad5": SetPad5,
    "PerformPad5": PerformPad5,
    "ShowPic1": ShowPic1,
    "Terminate": Terminate,
    "ShowPic2": ShowPic2,
    "ShowPic3": ShowPic3,
    "ShowPic4": ShowPic4,
    "ShowPic5": ShowPic5,
    "ShowPic6": ShowPic6,
    "ShowPic7": ShowPic7,
};

var Inclinaison, Unmounted, MenuBase, CarossTranspa, ArriereOuvert, MenuStep;



// utility function envoked by almost all V3D-specific puzzles
// filter off some non-mesh types
function notIgnoredObj(obj) {
    return (obj.type !== "AmbientLight" && obj.name !== ""
            && !(obj.isMesh && obj.isMaterialGeneratedMesh));
}


// utility function envoked by almost all V3D-specific puzzles
// find first occurence of the object by its name
function getObjectByName(objName) {
    var objFound;
    var runTime = _pGlob !== undefined;
    objFound = runTime ? _pGlob.objCache[objName] : null;

    if (objFound && objFound.name === objName)
        return objFound;

    appInstance.scene.traverse(function(obj) {
        if (!objFound && notIgnoredObj(obj) && (obj.name == objName)) {
            objFound = obj;
            if (runTime) {
                _pGlob.objCache[objName] = objFound;
            }
        }
    });
    return objFound;
}


// utility function envoked by almost all V3D-specific puzzles
// retrieve all objects on the scene
function getAllObjectNames() {
    var objNameList = [];
    appInstance.scene.traverse(function(obj) {
        if (notIgnoredObj(obj))
            objNameList.push(obj.name)
    });
    return objNameList;
}


// utility function envoked by almost all V3D-specific puzzles
// retrieve all objects which belong to the group
function getObjectNamesByGroupName(targetGroupName) {
    var objNameList = [];
    appInstance.scene.traverse(function(obj){
        if (notIgnoredObj(obj)) {
            var groupNames = obj.groupNames;
            if (!groupNames)
                return;
            for (var i = 0; i < groupNames.length; i++) {
                var groupName = groupNames[i];
                if (groupName == targetGroupName) {
                    objNameList.push(obj.name);
                }
            }
        }
    });
    return objNameList;
}


// utility function envoked by almost all V3D-specific puzzles
// process object input, which can be either single obj or array of objects, or a group
function retrieveObjectNames(objNames) {
    var acc = [];
    retrieveObjectNamesAcc(objNames, acc);
    return acc;
}

function retrieveObjectNamesAcc(currObjNames, acc) {
    if (typeof currObjNames == "string") {
        acc.push(currObjNames);
    } else if (Array.isArray(currObjNames) && currObjNames[0] == "GROUP") {
        var newObj = getObjectNamesByGroupName(currObjNames[1]);
        for (var i = 0; i < newObj.length; i++)
            acc.push(newObj[i]);
    } else if (Array.isArray(currObjNames) && currObjNames[0] == "ALL_OBJECTS") {
        var newObj = getAllObjectNames();
        for (var i = 0; i < newObj.length; i++)
            acc.push(newObj[i]);
    } else if (Array.isArray(currObjNames)) {
        for (var i = 0; i < currObjNames.length; i++)
            retrieveObjectNamesAcc(currObjNames[i], acc);
    }
}




// getAnimations puzzle
function getAnimations(objNames) {
    objNames = retrieveObjectNames(objNames);
    if (!objNames)
        return;
    var animations = [];
    for (var i = 0; i < objNames.length; i++) {
        var objName = objNames[i];
        if (!objName)
            continue;
        // use objName as animName - for now we have one-to-one match
        var action = v3d.SceneUtils.getAnimationActionByName(appInstance, objName);
        if (action)
            animations.push(objName);
    }
    return animations;
}



/**
 * Get a scene that contains the root of the given action.
 */
function getSceneByAction(action) {
    var root = action.getRoot();
    var scene = root.type == "Scene" ? root : null;
    root.traverseAncestors(function(ancObj) {
        if (ancObj.type == "Scene") {
            scene = ancObj;
        }
    });
    return scene;
}



/**
 * Get the current scene's framerate.
 */
function getSceneAnimFrameRate(scene) {
    if (scene && "v3d" in scene.userData && "animFrameRate" in scene.userData.v3d) {
        return scene.userData.v3d.animFrameRate;
    }
    return 24;
}



var initAnimationMixer = function() {

    function onMixerFinished(e) {
        var cb = _pGlob.animMixerCallbacks;
        var found = [];
        for (var i = 0; i < cb.length; i++) {
            if (cb[i][0] == e.action) {
                cb[i][0] = null; // desactivate
                found.push(cb[i][1]);
            }
        }
        for (var i = 0; i < found.length; i++) {
            found[i]();
        }
    }

    return function initAnimationMixer() {
        if (appInstance.mixer && !appInstance.mixer.hasEventListener('finished', onMixerFinished))
            appInstance.mixer.addEventListener('finished', onMixerFinished);
    };

}();



// animation puzzles
function operateAnimation(operation, animations, from, to, loop, speed, callback, isPlayAnimCompat, rev) {
    if (!animations)
        return;
    // input can be either single obj or array of objects
    if (typeof animations == "string")
        animations = [animations];

    function processAnimation(animName) {
        var action = v3d.SceneUtils.getAnimationActionByName(appInstance, animName);
        if (!action)
            return;
        switch (operation) {
        case 'PLAY':
            if (!action.isRunning()) {
                action.reset();
                if (loop && (loop != "AUTO"))
                    action.loop = v3d[loop];
                var scene = getSceneByAction(action);
                var frameRate = getSceneAnimFrameRate(scene);

                // compatibility reasons: deprecated playAnimation puzzles don't
                // change repetitions
                if (!isPlayAnimCompat) {
                    action.repetitions = Infinity;
                }

                var timeScale = Math.abs(parseFloat(speed));
                if (rev)
                    timeScale *= -1;

                action.timeScale = timeScale;
                action.timeStart = from !== null ? from/frameRate : 0;
                if (to !== null) {
                    action.getClip().duration = to/frameRate;
                } else {
                    action.getClip().resetDuration();
                }
                action.time = timeScale >= 0 ? action.timeStart : action.getClip().duration;

                action.paused = false;
                action.play();

                // push unique callbacks only
                var callbacks = _pGlob.animMixerCallbacks;
                var found = false;

                for (var j = 0; j < callbacks.length; j++)
                    if (callbacks[j][0] == action && callbacks[j][1] == callback)
                        found = true;

                if (!found)
                    _pGlob.animMixerCallbacks.push([action, callback]);
            }
            break;
        case 'STOP':
            action.stop();

            // remove callbacks
            var callbacks = _pGlob.animMixerCallbacks;
            for (var j = 0; j < callbacks.length; j++)
                if (callbacks[j][0] == action) {
                    callbacks.splice(j, 1);
                    j--
                }

            break;
        case 'PAUSE':
            action.paused = true;
            break;
        case 'RESUME':
            action.paused = false;
            break;
        case 'SET_FRAME':
            var scene = getSceneByAction(action);
            var frameRate = getSceneAnimFrameRate(scene);
            action.time = from ? from/frameRate : 0;
            action.play();
            action.paused = true;
            break;
        }
    }

    for (var i = 0; i < animations.length; i++) {
        var animName = animations[i];
        if (animName)
            processAnimation(animName);
    }

    initAnimationMixer();
}



// outline puzzle
function outline(objNames, doWhat) {
    objNames = retrieveObjectNames(objNames);
    if (!objNames)
        return;
    if (!appInstance.postprocessing || !appInstance.postprocessing.outlinePass)
        return;
    var outlineArray = appInstance.postprocessing.outlinePass.selectedObjects;
    for (var i = 0; i < objNames.length; i++) {
        var objName = objNames[i];
        var obj = getObjectByName(objName);
        if (!obj)
            continue;
        if (doWhat == "ENABLE") {
            if (outlineArray.indexOf(obj) == -1)
                outlineArray.push(obj);
        } else {
            var index = outlineArray.indexOf(obj);
            if (index > -1)
                outlineArray.splice(index, 1);
        }
    }
}



// bloom puzzle
function bloom(threshold, strength, radius) {
    appInstance.enablePostprocessing([{
        type: 'bloom',
        threshold: threshold,
        strength: strength,
        radius: radius
    }]);
}




/**
 * Retrieve coordinate system from the loaded scene
 */
function getCoordSystem() {
    var scene = appInstance.scene;

    if (scene && "v3d" in scene.userData && "coordSystem" in scene.userData.v3d) {
        return scene.userData.v3d.coordSystem;
    } else {
        // COMPAT: <2.17, consider replacing to 'Y_UP_RIGHT' for scenes with unknown origin
        return 'Z_UP_RIGHT';
    }
}


/**
 * Transform coordinates from one space to another
 * Can be used with Vector3 or Euler.
 */
function coordsTransform(coords, from, to, noSignChange) {

    if (from == to)
        return coords;

    var y = coords.y, z = coords.z;

    if (from == 'Z_UP_RIGHT' && to == 'Y_UP_RIGHT') {
        coords.y = z;
        coords.z = noSignChange ? y : -y;
    } else if (from == 'Y_UP_RIGHT' && to == 'Z_UP_RIGHT') {
        coords.y = noSignChange ? z : -z;
        coords.z = y;
    } else {
        console.error('coordsTransform: Unsupported coordinate space');
    }

    return coords;
}


/**
 * Verge3D euler rotation to Blender/Max shortest.
 * 1) Convert from intrinsic rotation (v3d) to extrinsic XYZ (Blender/Max default
 *    order) via reversion: XYZ -> ZYX
 * 2) swizzle ZYX->YZX
 * 3) choose the shortest rotation to resemble Blender's behavior
 */
var eulerV3DToBlenderShortest = function() {

    var eulerTmp = new v3d.Euler();
    var eulerTmp2 = new v3d.Euler();
    var vec3Tmp = new v3d.Vector3();

    return function(euler, dest) {

        var eulerBlender = eulerTmp.copy(euler).reorder('YZX');
        var eulerBlenderAlt = eulerTmp2.copy(eulerBlender).makeAlternative();

        var len = eulerBlender.toVector3(vec3Tmp).lengthSq();
        var lenAlt = eulerBlenderAlt.toVector3(vec3Tmp).lengthSq();

        dest.copy(len < lenAlt ? eulerBlender : eulerBlenderAlt);
        return coordsTransform(dest, 'Y_UP_RIGHT', 'Z_UP_RIGHT');
    }

}();




// tweenCamera puzzle
function tweenCamera(posOrObj, targetOrObj, duration, doSlot, movementType) {

    if (Array.isArray(posOrObj)) {
        var worldPos = _pGlob.vec3Tmp.fromArray(posOrObj);
        worldPos = coordsTransform(worldPos, getCoordSystem(), 'Y_UP_RIGHT');
    } else if (posOrObj) {
        var posObj = getObjectByName(posOrObj);
        if (!posObj) return;
        var worldPos = posObj.getWorldPosition(_pGlob.vec3Tmp);
    } else {
        // empty input means: don't change the position
        var worldPos = appInstance.camera.getWorldPosition(_pGlob.vec3Tmp);
    }

    if (Array.isArray(targetOrObj)) {
        var worldTarget = _pGlob.vec3Tmp2.fromArray(targetOrObj);
        worldTarget = coordsTransform(worldTarget, getCoordSystem(), 'Y_UP_RIGHT');
    } else {
        var targObj = getObjectByName(targetOrObj);
        if (!targObj) return;
        var worldTarget = targObj.getWorldPosition(_pGlob.vec3Tmp2);
    }

    duration = Math.max(0, duration);

    if (appInstance.controls && appInstance.controls.tween) {
        // orbit and flying cameras
        if (!appInstance.controls.inTween) {
            appInstance.controls.tween(worldPos, worldTarget, duration, doSlot,
                    movementType);
        }
    } else {
        // TODO: static camera, just position it for now
        if (appInstance.camera.parent) {
            appInstance.camera.parent.worldToLocal(worldPos);
        }
        appInstance.camera.position.copy(worldPos);
        appInstance.camera.lookAt(worldTarget);
        doSlot();
    }
}



// setTimeout puzzle
function registerSetTimeout(timeout, callback) {
    window.setTimeout(callback, 1000 * timeout);
}



// utility functions envoked by the HTML puzzles
function getElements(ids, isParent) {
    var elems = [];
    if (Array.isArray(ids) && ids[0] != 'CONTAINER' && ids[0] != 'WINDOW' &&
        ids[0] != 'DOCUMENT' && ids[0] != 'BODY' && ids[0] != 'QUERYSELECTOR') {
        for (var i = 0; i < ids.length; i++)
            elems.push(getElement(ids[i], isParent));
    } else {
        elems.push(getElement(ids, isParent));
    }
    return elems;
}

function getElement(id, isParent) {
    var elem;
    if (Array.isArray(id) && id[0] == 'CONTAINER') {
        if (appInstance !== null) {
            elem = appInstance.container;
        } else if (typeof _initGlob !== 'undefined') {
            // if we are on the initialization stage, we still can have access
            // to the container element
            var id = _initGlob.container;
            if (isParent) {
                elem = parent.document.getElementById(id);
            } else {
                elem = document.getElementById(id);
            }
        }
    } else if (Array.isArray(id) && id[0] == 'WINDOW') {
        if (isParent)
            elem = parent;
        else
            elem = window;
    } else if (Array.isArray(id) && id[0] == 'DOCUMENT') {
        if (isParent)
            elem = parent.document;
        else
            elem = document;
    } else if (Array.isArray(id) && id[0] == 'BODY') {
        if (isParent)
            elem = parent.document.body;
        else
            elem = document.body;
    } else if (Array.isArray(id) && id[0] == 'QUERYSELECTOR') {
        if (isParent)
            elem = parent.document.querySelector(id);
        else
            elem = document.querySelector(id);
    } else {
        if (isParent)
            elem = parent.document.getElementById(id);
        else
            elem = document.getElementById(id);
    }
    return elem;
}



// eventHTMLElem puzzle
function eventHTMLElem(eventType, ids, isParent, callback) {
    var elems = getElements(ids, isParent);
    for (var i = 0; i < elems.length; i++) {
        var elem = elems[i];
        if (!elem)
            continue;
        elem.addEventListener(eventType, callback, false);
    }
}



// show and hide puzzles
function changeVis(objNames, bool) {
    objNames = retrieveObjectNames(objNames);
    if (!objNames)
        return;
    for (var i = 0; i < objNames.length; i++) {
        var objName = objNames[i]
        if (!objName)
            continue;
        var obj = getObjectByName(objName);
        if (!obj)
            continue;
        obj.visible = bool;
    }
}



// setHTMLElemStyle puzzle
function setHTMLElemStyle(prop, value, ids, isParent) {
    var elems = getElements(ids, isParent);
    for (var i = 0; i < elems.length; i++) {
        var elem = elems[i];
        if (!elem || !elem.style)
            continue;
        elem.style[prop] = value;
    }
}


// Describe this function...
function Reboot() {
  tweenCamera('CameraMechOpen', 'FocusMain', 2, function() {
    changeVis(['GROUP', 'Pedal&PowerHide'], true);
    changeVis(['GROUP', 'BoltMachine'], true);
    outline(['ALL_OBJECTS'], 'DISABLE');
    setHTMLElemStyle('visibility', 'hidden', 'ActionTap', true);
    MenuBase = 0;
    MenuStep = 0;
  }, 0);
  Unmount();
  Unincline();
  CloseAR();
  shadeBodyOff();
}

// Describe this function...
function Unmount() {
  if (Unmounted == true) {

    operateAnimation('PLAY', getAnimations(['GROUP', 'BoltMachine']), 950, 1050, 'LoopOnce', 2,
            function() {
      Unmounted = false;
    }, undefined, true);


    operateAnimation('SET_FRAME', ['BoltPiedL', 'BoltPiedR'], 800, null, 'AUTO', 1,
            function() {}, undefined, false);

        }
}

// Describe this function...
function Unincline() {
  if (Inclinaison == true) {

    operateAnimation('PLAY', getAnimations(['GROUP', 'TiltMachineAnime']), 670, 700, 'LoopOnce', 1,
            function() {
      Inclinaison = false;
    }, undefined, false);

        }
}

// Describe this function...
function OpenAR() {
  if (ArriereOuvert == false) {

    operateAnimation('PLAY', getAnimations(['GROUP', 'CapotAR']), 0, 80, 'LoopOnce', 1,
            function() {
      ArriereOuvert = true;
    }, undefined, false);

        }
}

// Describe this function...
function CloseAR() {
  if (ArriereOuvert == true) {

    operateAnimation('PLAY', getAnimations(['GROUP', 'CapotAR']), 0, 80, 'LoopOnce', 1.5,
            function() {
      ArriereOuvert = false;
    }, undefined, true);

        }
}


function matGetValues(matName) {

    var mat = v3d.SceneUtils.getMaterialByName(appInstance, matName);
    if (!mat)
        return [];

    if (mat.isMeshNodeMaterial)
        return Object.keys(mat.nodeValueMap);
    else if (mat.isMeshStandardMaterial)
        return ['metalness', 'roughness', 'bumpScale', 'emissiveIntensity', 'envMapIntensity'];
    else
        return [];
}



// setMaterialValue puzzle
function setMaterialValue(matName, valName, value) {

    var values = matGetValues(matName);
    if (values.indexOf(valName) < 0)
        return;

    var mats = v3d.SceneUtils.getMaterialsByName(appInstance, matName);

    for (var i = 0; i < mats.length; i++) {
        var mat = mats[i];

        if (mat.isMeshNodeMaterial) {
            var valIdx = mat.nodeValueMap[valName];
            mat.nodeValue[valIdx] = Number(value);
        } else
            mat[valName] = Number(value);

        if (mat === appInstance.worldMaterial)
            appInstance.updateEnvironment(mat);
    }
}



// Copyright (c) 2010-2019 Tween.js authors.
// Easing equations Copyright (c) 2001 Robert Penner http://robertpenner.com/easing/
// Code copied from https://cdnjs.cloudflare.com/ajax/libs/tween.js/17.3.0/Tween.min.js

var _Group=function(){this._tweens={},this._tweensAddedDuringUpdate={}};_Group.prototype={getAll:function(){return Object.keys(this._tweens).map(function(t){return this._tweens[t]}.bind(this))},removeAll:function(){this._tweens={}},add:function(t){this._tweens[t.getId()]=t,this._tweensAddedDuringUpdate[t.getId()]=t},remove:function(t){delete this._tweens[t.getId()],delete this._tweensAddedDuringUpdate[t.getId()]},update:function(t,n){var e=Object.keys(this._tweens);
if(0===e.length)return!1;for(t=void 0!==t?t:TWEEN.now();0<e.length;){this._tweensAddedDuringUpdate={};for(var i=0;i<e.length;i++){var r=this._tweens[e[i]];r&&!1===r.update(t)&&(r._isPlaying=!1,n||delete this._tweens[e[i]])}e=Object.keys(this._tweensAddedDuringUpdate)}return!0}};var TWEEN=new _Group;TWEEN.Group=_Group,TWEEN._nextId=0,TWEEN.nextId=function(){return TWEEN._nextId++},"undefined"==typeof window&&"undefined"!=typeof process&&process.hrtime?TWEEN.now=function(){var t=process.hrtime();
return 1e3*t[0]+t[1]/1e6}:"undefined"!=typeof window&&void 0!==window.performance&&void 0!==window.performance.now?TWEEN.now=window.performance.now.bind(window.performance):void 0!==Date.now?TWEEN.now=Date.now:TWEEN.now=function(){return(new Date).getTime()},TWEEN.Tween=function(t,n){this._object=t,this._valuesStart={},this._valuesEnd={},this._valuesStartRepeat={},this._duration=1e3,this._repeat=0,this._repeatDelayTime=void 0,this._yoyo=!1,this._isPlaying=!1,this._reversed=!1,this._delayTime=0,
this._startTime=null,this._easingFunction=TWEEN.Easing.Linear.None,this._interpolationFunction=TWEEN.Interpolation.Linear,this._chainedTweens=[],this._onStartCallback=null,this._onStartCallbackFired=!1,this._onUpdateCallback=null,this._onCompleteCallback=null,this._onStopCallback=null,this._group=n||TWEEN,this._id=TWEEN.nextId()},TWEEN.Tween.prototype={getId:function(){return this._id},isPlaying:function(){return this._isPlaying},to:function(t,n){return this._valuesEnd=t,void 0!==n&&(this._duration=n),this},start:function(t){for(var n in this._group.add(this),this._isPlaying=!0,this._onStartCallbackFired=!1,this._startTime=void 0!==t?"string"==typeof t?TWEEN.now()+parseFloat(t):t:TWEEN.now(),this._startTime+=this._delayTime,this._valuesEnd){if(this._valuesEnd[n]instanceof Array){if(0===this._valuesEnd[n].length)continue;
this._valuesEnd[n]=[this._object[n]].concat(this._valuesEnd[n])}void 0!==this._object[n]&&(this._valuesStart[n]=this._object[n],this._valuesStart[n]instanceof Array==!1&&(this._valuesStart[n]*=1),this._valuesStartRepeat[n]=this._valuesStart[n]||0)}return this},stop:function(){return this._isPlaying&&(this._group.remove(this),this._isPlaying=!1,null!==this._onStopCallback&&this._onStopCallback(this._object),this.stopChainedTweens()),this},end:function(){return this.update(this._startTime+this._duration),this},stopChainedTweens:function(){for(var t=0,n=this._chainedTweens.length;t<n;
t++)this._chainedTweens[t].stop()},group:function(t){return this._group=t,this},delay:function(t){return this._delayTime=t,this},repeat:function(t){return this._repeat=t,this},repeatDelay:function(t){return this._repeatDelayTime=t,this},yoyo:function(t){return this._yoyo=t,this},easing:function(t){return this._easingFunction=t,this},interpolation:function(t){return this._interpolationFunction=t,this},chain:function(){return this._chainedTweens=arguments,this},onStart:function(t){return this._onStartCallback=t,this},onUpdate:function(t){return this._onUpdateCallback=t,this},onComplete:function(t){return this._onCompleteCallback=t,this},onStop:function(t){return this._onStopCallback=t,this},update:function(t){var n,e,i;if(t<this._startTime)return!0;
for(n in!1===this._onStartCallbackFired&&(null!==this._onStartCallback&&this._onStartCallback(this._object),this._onStartCallbackFired=!0),e=(t-this._startTime)/this._duration,e=0===this._duration||1<e?1:e,i=this._easingFunction(e),this._valuesEnd)if(void 0!==this._valuesStart[n]){var r=this._valuesStart[n]||0,a=this._valuesEnd[n];a instanceof Array?this._object[n]=this._interpolationFunction(a,i):("string"==typeof a&&(a="+"===a.charAt(0)||"-"===a.charAt(0)?r+parseFloat(a):parseFloat(a)),"number"==typeof a&&(this._object[n]=r+(a-r)*i))}if(null!==this._onUpdateCallback&&this._onUpdateCallback(this._object),1!==e)return!0;
if(0<this._repeat){for(n in isFinite(this._repeat)&&this._repeat--,this._valuesStartRepeat){if("string"==typeof this._valuesEnd[n]&&(this._valuesStartRepeat[n]=this._valuesStartRepeat[n]+parseFloat(this._valuesEnd[n])),this._yoyo){var s=this._valuesStartRepeat[n];this._valuesStartRepeat[n]=this._valuesEnd[n],this._valuesEnd[n]=s}this._valuesStart[n]=this._valuesStartRepeat[n]}return this._yoyo&&(this._reversed=!this._reversed),void 0!==this._repeatDelayTime?this._startTime=t+this._repeatDelayTime:this._startTime=t+this._delayTime,!0}null!==this._onCompleteCallback&&this._onCompleteCallback(this._object);for(var o=0,u=this._chainedTweens.length;o<u;o++)this._chainedTweens[o].start(this._startTime+this._duration);
return!1}},TWEEN.Easing={Linear:{None:function(t){return t}},Quadratic:{In:function(t){return t*t},Out:function(t){return t*(2-t)},InOut:function(t){return(t*=2)<1?.5*t*t:-.5*(--t*(t-2)-1)}},Cubic:{In:function(t){return t*t*t},Out:function(t){return--t*t*t+1},InOut:function(t){return(t*=2)<1?.5*t*t*t:.5*((t-=2)*t*t+2)}},Quartic:{In:function(t){return t*t*t*t},Out:function(t){return 1- --t*t*t*t},InOut:function(t){return(t*=2)<1?.5*t*t*t*t:-.5*((t-=2)*t*t*t-2)}},Quintic:{In:function(t){return t*t*t*t*t},Out:function(t){return--t*t*t*t*t+1},InOut:function(t){return(t*=2)<1?.5*t*t*t*t*t:.5*((t-=2)*t*t*t*t+2)}},Sinusoidal:{In:function(t){return 1-Math.cos(t*Math.PI/2)},Out:function(t){return Math.sin(t*Math.PI/2)},InOut:function(t){return.5*(1-Math.cos(Math.PI*t))}},Exponential:{In:function(t){return 0===t?0:Math.pow(1024,t-1)},Out:function(t){return 1===t?1:1-Math.pow(2,-10*t)},
InOut:function(t){return 0===t?0:1===t?1:(t*=2)<1?.5*Math.pow(1024,t-1):.5*(2-Math.pow(2,-10*(t-1)))}},Circular:{In:function(t){return 1-Math.sqrt(1-t*t)},Out:function(t){return Math.sqrt(1- --t*t)},InOut:function(t){return(t*=2)<1?-.5*(Math.sqrt(1-t*t)-1):.5*(Math.sqrt(1-(t-=2)*t)+1)}},Elastic:{In:function(t){return 0===t?0:1===t?1:-Math.pow(2,10*(t-1))*Math.sin(5*(t-1.1)*Math.PI)},Out:function(t){return 0===t?0:1===t?1:Math.pow(2,-10*t)*Math.sin(5*(t-.1)*Math.PI)+1},InOut:function(t){return 0===t?0:1===t?1:(t*=2)<1?-.5*Math.pow(2,10*(t-1))*Math.sin(5*(t-1.1)*Math.PI):.5*Math.pow(2,-10*(t-1))*Math.sin(5*(t-1.1)*Math.PI)+1}},Back:{In:function(t){return t*t*(2.70158*t-1.70158)},Out:function(t){return--t*t*(2.70158*t+1.70158)+1},InOut:function(t){var n=2.5949095;
return(t*=2)<1?t*t*((n+1)*t-n)*.5:.5*((t-=2)*t*((n+1)*t+n)+2)}},Bounce:{In:function(t){return 1-TWEEN.Easing.Bounce.Out(1-t)},Out:function(t){return t<1/2.75?7.5625*t*t:t<2/2.75?7.5625*(t-=1.5/2.75)*t+.75:t<2.5/2.75?7.5625*(t-=2.25/2.75)*t+.9375:7.5625*(t-=2.625/2.75)*t+.984375},InOut:function(t){return t<.5?.5*TWEEN.Easing.Bounce.In(2*t):.5*TWEEN.Easing.Bounce.Out(2*t-1)+.5}}},TWEEN.Interpolation={Linear:function(t,n){var e=t.length-1,i=e*n,r=Math.floor(i),a=TWEEN.Interpolation.Utils.Linear;return n<0?a(t[0],t[1],i):1<n?a(t[e],t[e-1],e-i):a(t[r],t[e<r+1?e:r+1],i-r)},Bezier:function(t,n){for(var e=0,i=t.length-1,r=Math.pow,a=TWEEN.Interpolation.Utils.Bernstein,s=0;s<=i;s++)e+=r(1-n,i-s)*r(n,s)*t[s]*a(i,s);return e},CatmullRom:function(t,n){var e=t.length-1,i=e*n,r=Math.floor(i),a=TWEEN.Interpolation.Utils.CatmullRom;
return t[0]===t[e]?(n<0&&(r=Math.floor(i=e*(1+n))),a(t[(r-1+e)%e],t[r],t[(r+1)%e],t[(r+2)%e],i-r)):n<0?t[0]-(a(t[0],t[0],t[1],t[1],-i)-t[0]):1<n?t[e]-(a(t[e],t[e],t[e-1],t[e-1],i-e)-t[e]):a(t[r?r-1:0],t[r],t[e<r+1?e:r+1],t[e<r+2?e:r+2],i-r)},Utils:{Linear:function(t,n,e){return(n-t)*e+t},Bernstein:function(t,n){var e=TWEEN.Interpolation.Utils.Factorial;return e(t)/e(n)/e(t-n)},Factorial:function(){var i=[1];return function(t){var n=1;if(i[t])return i[t];for(var e=t;1<e;e--)n*=e;return i[t]=n}}(),CatmullRom:function(t,n,e,i,r){var a=.5*(e-t),s=.5*(i-n),o=r*r;return(2*n-2*e+a+s)*(r*o)+(-3*n+3*e-2*a-s)*o+a*r+n}}},function(t){"function"==typeof define&&define.amd?define([],function(){return TWEEN}):"undefined"!=typeof module&&"object"==typeof exports?module.exports=TWEEN:void 0!==t&&(t.TWEEN=TWEEN)}(this);



// animateParam puzzle
appInstance.renderCallbacks.push(function() { TWEEN.update(); });



// animateParam puzzle
function animateParam(from, to, duration, easing, easing2, repeat, yoyo, on_update, when_finished) {

    var mode = easing == "Linear" ?
        TWEEN.Easing.Linear.None : TWEEN.Easing[easing][easing2];

    var tweenObject = (typeof from != "number");

    if (!tweenObject) { // number
        from = [from];
        to = [to];
    }

    var tween = new TWEEN.Tween(from)
                    .to(to, duration * 1000)
                    .easing(mode)
                    .repeat(repeat)
                    .yoyo(yoyo)
                    .onUpdate(function (object) {
                        if (tweenObject)
                            _pGlob.animateParamUpdate = object;
                        else // number
                            _pGlob.animateParamUpdate = object[0];
                        on_update();
                    })
                    .onComplete(function (object) {
                        when_finished();
                    })
                    .start();
}


// Describe this function...
function shadeBodyOn() {
  if (CarossTranspa == false) {

    animateParam(1, 0.3, 2, 'Linear', 'InOut', 0, false,
        function() {
      setMaterialValue('BluePaintCarosse', 'Value', _pGlob.animateParamUpdate);
    },
        function() {
      CarossTranspa = true;
    });

        }
}

// Describe this function...
function Setpad1() {
  ShowPic1();
  setHTMLElemStyle('visibility', 'visible', 'ActionTap', true);
  setHTMLElemStyle('visibility', 'hidden', ['Boutonspares', 'Boutonsparesout'], true);
  shadeBodyOff();
  CloseAR();
  setMaterialValue('BlancMeca', 'Value', 1);
  tweenCamera('CameraMechOpen', 'FocusMain', 2, function() {

    operateAnimation('SET_FRAME', getAnimations(['ALL_OBJECTS']), 0, null, 'AUTO', 1,
            function() {}, undefined, false);

        changeVis(['ALL_OBJECTS'], true);
    outline(['ALL_OBJECTS'], 'DISABLE');
    outline(['GROUP', 'HighlightRearOpen'], 'ENABLE');
    MenuStep = 1;
  }, 0);
}

// Describe this function...
function SetMount1() {
  ShowPic1();
  setHTMLElemStyle('visibility', 'hidden', ['Boutonspares', 'Boutonsparesout'], true);
  setHTMLElemStyle('visibility', 'hidden', 'Warning', true);
  tweenCamera('CameraMechOpen', 'FocusMain', 2, function() {

    operateAnimation('SET_FRAME', getAnimations(['ALL_OBJECTS']), 0, null, 'AUTO', 1,
            function() {}, undefined, false);


    operateAnimation('SET_FRAME', getAnimations(['GROUP', 'BoltMachine']), 800, null, 'AUTO', 1,
            function() {}, undefined, false);

        changeVis(['ALL_OBJECTS'], true);
    changeVis(['GROUP', 'Pedal&PowerHide'], false);
    outline(['ALL_OBJECTS'], 'DISABLE');
    registerSetTimeout(1, function() {
      outline(['GROUP', 'BoltMachine'], 'ENABLE');
      setHTMLElemStyle('visibility', 'visible', 'ActionTap', true);
    });
    MenuStep = 1;
  }, 0);
  Unmount();
}

// Describe this function...
function SetTilt1() {
  ShowPic1();
  setHTMLElemStyle('visibility', 'visible', 'ActionTap', true);
  setHTMLElemStyle('visibility', 'hidden', ['Boutonspares', 'Boutonsparesout'], true);
  tweenCamera('CameraMechOpen', 'FocusMain', 2, function() {

    operateAnimation('SET_FRAME', getAnimations(['ALL_OBJECTS']), 0, null, 'AUTO', 1,
            function() {}, undefined, false);


    operateAnimation('SET_FRAME', getAnimations(['GROUP', 'TiltMachineAnime']), 400, null, 'AUTO', 1,
            function() {}, undefined, false);

        changeVis(['ALL_OBJECTS'], true);
    outline(['ALL_OBJECTS'], 'DISABLE');
    outline(['GROUP', 'AngleSet'], 'ENABLE');
    MenuStep = 1;
  }, 0);
  Unincline();
  shadeBodyOff();
}

// Describe this function...
function shadeBodyOff() {
  if (CarossTranspa == true) {

    animateParam(0.3, 1, 2, 'Linear', 'InOut', 0, false,
        function() {
      setMaterialValue('BluePaintCarosse', 'Value', _pGlob.animateParamUpdate);
    },
        function() {
      CarossTranspa = false;
    });

        }
}

// Describe this function...
function PerformPad1() {
  setHTMLElemStyle('visibility', 'hidden', 'ActionTap', true);
  tweenCamera('CameraTiltStart', 'FocusMain', 2, function() {}, 0);
  if (ArriereOuvert == false) {

    operateAnimation('PLAY', getAnimations(['GROUP', 'CapotAR']), 0, 32, 'LoopOnce', 1,
            function() {
      ArriereOuvert = true;

      operateAnimation('PLAY', getAnimations(['GROUP', 'ArrowBec1']), null, null, 'AUTO', 1,
              function() {}, undefined, false);

          outline(['GROUP', 'ArrowBec1'], 'ENABLE');
    }, undefined, false);

        }

  animateParam(1, 0.3, 2, 'Linear', 'InOut', 0, false,
      function() {
    setMaterialValue('BluePaintCarosse', 'Value', _pGlob.animateParamUpdate);
  },
      function() {
    CarossTranspa = true;
    outline(['GROUP', 'HighlightRearOpen'], 'DISABLE');
    outline('becquille', 'ENABLE');
    MenuStep = 2;
    ShowPic2();
    setHTMLElemStyle('visibility', 'visible', 'ActionTap', true);
  });

      }

// Describe this function...
function PerformTilt1() {
  setHTMLElemStyle('visibility', 'hidden', 'ActionTap', true);
  shadeBodyOn();
  tweenCamera('CameraTiltStart', 'FocusMain', 2, function() {
    outline(['GROUP', 'AngleSet'], 'DISABLE');
    outline('AngleSetter', 'ENABLE');

    operateAnimation('SET_FRAME', getAnimations(['ALL_OBJECTS']), 0, null, 'AUTO', 1,
            function() {}, undefined, false);


    operateAnimation('SET_FRAME', getAnimations(['GROUP', 'TiltMachineAnime']), 400, null, 'AUTO', 1,
            function() {}, undefined, false);


    operateAnimation('PLAY', getAnimations(['GROUP', 'ArrowAngle']), 0, 150, 'AUTO', 1,
            function() {}, undefined, true);

        CarossTranspa = true;
    outline(['GROUP', 'ArrowAngle'], 'ENABLE');
    ShowPic2();
    MenuStep = 2;
    setHTMLElemStyle('visibility', 'visible', 'ActionTap', true);
  }, 0);
}

// Describe this function...
function PerformMount1() {
  setHTMLElemStyle('visibility', 'hidden', 'ActionTap', true);
  tweenCamera('CameraRemoveStart', 'FocusMain', 2, function() {
    ShowPic2();
    MenuStep = 2;
    setHTMLElemStyle('visibility', 'visible', 'ActionTap', true);
  }, 0);
}

// Describe this function...
function SetPad2() {
  ShowPic2();
  setHTMLElemStyle('visibility', 'visible', 'ActionTap', true);
  tweenCamera('CameraTiltStart', 'FocusMain', 2, function() {

    operateAnimation('SET_FRAME', getAnimations(['ALL_OBJECTS']), 80, null, 'AUTO', 1,
            function() {}, undefined, false);

        }, 0);
  shadeBodyOn();
  setHTMLElemStyle('visibility', 'hidden', ['Boutonspares', 'Boutonsparesout'], true);
  setMaterialValue('BlancMeca', 'Value', 1);
  changeVis(['ALL_OBJECTS'], true);
  outline(['ALL_OBJECTS'], 'DISABLE');
  outline('becquille', 'ENABLE');
  outline(['GROUP', 'ArrowBec1'], 'ENABLE');

  operateAnimation('PLAY', getAnimations(['GROUP', 'ArrowBec1']), null, null, 'AUTO', 1,
          function() {}, undefined, false);

      MenuStep = 2;
}

// Describe this function...
function SetMount2() {
  ShowPic2();
  setHTMLElemStyle('visibility', 'hidden', ['Boutonspares', 'Boutonsparesout'], true);
  setHTMLElemStyle('visibility', 'hidden', 'Warning', true);
  changeVis(['ALL_OBJECTS'], true);
  changeVis(['GROUP', 'Pedal&PowerHide'], false);
  outline(['ALL_OBJECTS'], 'DISABLE');
  outline(['GROUP', 'BoltMachine'], 'ENABLE');
  Unmount();
  tweenCamera('CameraRemoveStart', 'FocusMain', 2, function() {

    operateAnimation('SET_FRAME', getAnimations(['ALL_OBJECTS']), 0, null, 'AUTO', 1,
            function() {}, undefined, false);


    operateAnimation('SET_FRAME', getAnimations(['GROUP', 'BoltMachine']), 800, null, 'AUTO', 1,
            function() {}, undefined, false);

        MenuStep = 2;
    setHTMLElemStyle('visibility', 'visible', 'ActionTap', true);
  }, 0);
}

// Describe this function...
function SetTilt2() {
  ShowPic2();
  setHTMLElemStyle('visibility', 'visible', 'ActionTap', true);
  tweenCamera('CameraTiltStart', 'FocusMain', 2, function() {

    operateAnimation('SET_FRAME', getAnimations(['ALL_OBJECTS']), 0, null, 'AUTO', 1,
            function() {}, undefined, false);


    operateAnimation('SET_FRAME', getAnimations(['GROUP', 'TiltMachineAnime']), 400, null, 'AUTO', 1,
            function() {}, undefined, false);


    operateAnimation('PLAY', getAnimations(['GROUP', 'ArrowAngle']), 0, 150, 'AUTO', 1,
            function() {}, undefined, true);

        changeVis(['ALL_OBJECTS'], true);
    outline(['ALL_OBJECTS'], 'DISABLE');
    outline(['GROUP', 'ArrowAngle'], 'ENABLE');
    outline('AngleSetter', 'ENABLE');
    MenuStep = 2;
    setHTMLElemStyle('visibility', 'hidden', ['Boutonspares', 'Boutonsparesout'], true);
  }, 0);
  shadeBodyOn();
  Unincline();
}

// Describe this function...
function PerformPad2() {
  setHTMLElemStyle('visibility', 'hidden', 'ActionTap', true);

  operateAnimation('PLAY', getAnimations(['GROUP', 'CapotAR']), 32, 60, 'LoopOnce', 1,
          function() {
    registerSetTimeout(1, function() {
      outline(['GROUP', 'ArrowBec1'], 'DISABLE');
      outline('becquille', 'DISABLE');

      operateAnimation('STOP', getAnimations(['GROUP', 'ArrowBec1']), null, null, 'AUTO', 1,
              function() {}, undefined, false);

          registerSetTimeout(0.5, function() {
        tweenCamera('CameraFlapStart', 'FocusPad', 2, function() {
          outline(['GROUP', 'FlapHighlight'], 'ENABLE');
        }, 0);

        animateParam(0.3, 1, 2, 'Linear', 'InOut', 0, false,
            function() {
          setMaterialValue('BluePaintCarosse', 'Value', _pGlob.animateParamUpdate);
        },
            function() {
          CarossTranspa = false;

          animateParam(1, 0.25, 2, 'Linear', 'InOut', 0, false,
              function() {
            setMaterialValue('BlancMeca', 'Value', _pGlob.animateParamUpdate);
          },
              function() {});

              });

            ShowPic3();
        MenuStep = 3;
        setHTMLElemStyle('visibility', 'visible', 'ActionTap', true);
      });
    });
  }, undefined, false);

      }

// Describe this function...
function PerformTilt2() {
  setHTMLElemStyle('visibility', 'hidden', 'ActionTap', true);

  operateAnimation('PLAY', getAnimations(['GROUP', 'TiltMachineAnime']), 400, 420, 'LoopOnce', 1,
          function() {
    ShowPic3();
    setHTMLElemStyle('visibility', 'visible', 'ActionTap', true);
    MenuStep = 3;
  }, undefined, false);

      }

// Describe this function...
function PerformMount2() {
  setHTMLElemStyle('visibility', 'hidden', 'ActionTap', true);

  operateAnimation('PLAY', getAnimations(['GROUP', 'BoltMachine']), 800, 950, 'LoopOnce', 1,
          function() {
    outline(['ALL_OBJECTS'], 'DISABLE');
    changeVis(['BoltPiedL', 'BoltPiedR'], false);
    ShowPic3();
    MenuStep = 3;
    setHTMLElemStyle('visibility', 'visible', 'ActionTap', true);
  }, undefined, false);

      }

// Describe this function...
function SetPad3() {
  ShowPic3();
  setHTMLElemStyle('visibility', 'visible', 'ActionTap', true);
  tweenCamera('CameraFlapStart', 'FocusPad', 2, function() {
    outline(['GROUP', 'FlapHighlight'], 'ENABLE');
  }, 0);

  operateAnimation('SET_FRAME', getAnimations(['ALL_OBJECTS']), 60, null, 'AUTO', 1,
          function() {}, undefined, false);

      setMaterialValue('BlancMeca', 'Value', 0.25);
  setMaterialValue('BluePaintCarosse', 'Value', 1);
  setHTMLElemStyle('visibility', 'hidden', ['Boutonspares', 'Boutonsparesout'], true);
  changeVis(['ALL_OBJECTS'], true);
  outline(['ALL_OBJECTS'], 'DISABLE');
  outline(['GROUP', 'FlapHighlight'], 'ENABLE');
  MenuStep = 3;
}

// Describe this function...
function SetMount3() {
  ShowPic3();
  setHTMLElemStyle('visibility', 'visible', 'ActionTap', true);
  setHTMLElemStyle('visibility', 'hidden', ['Boutonspares', 'Boutonsparesout'], true);
  setHTMLElemStyle('visibility', 'hidden', 'Warning', true);
  changeVis(['ALL_OBJECTS'], true);
  outline(['ALL_OBJECTS'], 'DISABLE');
  changeVis(['GROUP', 'Pedal&PowerHide'], false);
  changeVis(['BoltPiedL', 'BoltPiedR'], false);
  tweenCamera('CameraRemoveStart', 'FocusMain', 2, function() {

    operateAnimation('SET_FRAME', getAnimations(['ALL_OBJECTS']), 0, null, 'AUTO', 1,
            function() {}, undefined, false);


    operateAnimation('SET_FRAME', getAnimations(['GROUP', 'BoltMachine']), 950, null, 'AUTO', 1,
            function() {}, undefined, false);

        MenuStep = 3;
  }, 0);
}

// Describe this function...
function SetTilt3() {
  ShowPic3();
  setHTMLElemStyle('visibility', 'visible', 'ActionTap', true);
  shadeBodyOn();
  tweenCamera('CameraTiltStart', 'FocusMain', 2, function() {

    operateAnimation('SET_FRAME', getAnimations(['ALL_OBJECTS']), 0, null, 'AUTO', 1,
            function() {}, undefined, false);


    operateAnimation('SET_FRAME', getAnimations(['GROUP', 'TiltMachineAnime']), 420, null, 'AUTO', 1,
            function() {}, undefined, false);

        setHTMLElemStyle('visibility', 'hidden', ['Boutonspares', 'Boutonsparesout'], true);
    MenuStep = 3;
  }, 0);
}

// Describe this function...
function PerformPad3() {
  setHTMLElemStyle('visibility', 'hidden', 'ActionTap', true);

  operateAnimation('PLAY', getAnimations(['GROUP', 'ArrowSprings']), null, null, 'AUTO', 1,
          function() {}, undefined, false);

      outline(['GROUP', 'ArrowSprings'], 'ENABLE');
  registerSetTimeout(3, function() {

    operateAnimation('PLAY', getAnimations(['GROUP', 'FlapAction']), 60, 80, 'AUTO', 1,
            function() {
      outline(['GROUP', 'ArrowSprings'], 'DISABLE');
      outline(['GROUP', 'FlapHighlight'], 'ENABLE');
    }, undefined, false);

        ShowPic4();
    MenuStep = 4;
    setHTMLElemStyle('visibility', 'visible', 'ActionTap', true);
  });
}

// Describe this function...
function PerformTilt3() {
  setHTMLElemStyle('visibility', 'hidden', 'ActionTap', true);

  operateAnimation('PLAY', getAnimations(['GROUP', 'TiltMachineAnime']), 420, 603, 'LoopOnce', 1,
          function() {
    outline(['GROUP', 'ArrowAngle'], 'DISABLE');
    ShowPic4();
    MenuStep = 4;
    Inclinaison = true;
    setHTMLElemStyle('visibility', 'visible', 'ActionTap', true);
  }, undefined, false);

      }

// Describe this function...
function PerformMount3() {
  setHTMLElemStyle('visibility', 'hidden', 'ActionTap', true);
  setHTMLElemStyle('visibility', 'visible', 'Warning', true);

  operateAnimation('PLAY', getAnimations(['GROUP', 'BoltMachine']), 950, 1030, 'LoopOnce', 1,
          function() {
    tweenCamera('CameraMechOpen', 'FocusMain', 2, function() {}, 0);
    outline(['ALL_OBJECTS'], 'DISABLE');
    Unmounted = true;
  }, undefined, false);

      }

// Describe this function...
function SetPad4() {
  ShowPic4();
  setHTMLElemStyle('visibility', 'visible', 'ActionTap', true);
  tweenCamera('CameraFlapStart', 'FocusPad', 2, function() {
    outline(['GROUP', 'FlapHighlight'], 'ENABLE');
  }, 0);

  operateAnimation('SET_FRAME', getAnimations(['ALL_OBJECTS']), 80, null, 'AUTO', 1,
          function() {}, undefined, false);

      setMaterialValue('BlancMeca', 'Value', 0.25);
  setMaterialValue('BluePaintCarosse', 'Value', 1);
  setHTMLElemStyle('visibility', 'hidden', ['Boutonspares', 'Boutonsparesout'], true);
  changeVis(['ALL_OBJECTS'], true);
  outline(['ALL_OBJECTS'], 'DISABLE');
  MenuStep = 4;
}

// Describe this function...
function SetTilt4() {
  Inclinaison = true;
  ShowPic4();
  setHTMLElemStyle('visibility', 'visible', 'ActionTap', true);
  shadeBodyOn();
  tweenCamera('CameraTiltStart', 'FocusMain', 2, function() {

    operateAnimation('SET_FRAME', getAnimations(['ALL_OBJECTS']), 0, null, 'AUTO', 1,
            function() {}, undefined, false);


    operateAnimation('SET_FRAME', getAnimations(['GROUP', 'TiltMachineAnime']), 603, null, 'AUTO', 1,
            function() {}, undefined, false);

        setHTMLElemStyle('visibility', 'hidden', ['Boutonspares', 'Boutonsparesout'], true);
    MenuStep = 4;
  }, 0);
}

// Describe this function...
function PerformPad4() {
  setHTMLElemStyle('visibility', 'hidden', 'ActionTap', true);
  outline(['GROUP', 'FlapHighlight'], 'DISABLE');

  operateAnimation('PLAY', getAnimations(['GROUP', 'FlapAction']), 80, 170, 'LoopOnce', 1,
          function() {
    outline(['GROUP', 'FlapHighlight'], 'ENABLE');
    registerSetTimeout(0.5, function() {

      operateAnimation('PLAY', getAnimations(['GROUP', 'FlapAction']), 170, 230, 'LoopOnce', 1,
              function() {
        registerSetTimeout(0.5, function() {

          operateAnimation('PLAY', getAnimations(['GROUP', 'FlapAction']), 230, 310, 'LoopOnce', 1,
                  function() {
            registerSetTimeout(1, function() {
              outline(['GROUP', 'FlapHighlight'], 'DISABLE');
            });
            registerSetTimeout(3, function() {
              tweenCamera('CameraMechOpen', 'FocusMain', 2, function() {}, 0);
              outline('becquille', 'ENABLE');
              outline(['GROUP', 'ArrowBec2'], 'ENABLE');

              operateAnimation('PLAY', getAnimations(['GROUP', 'ArrowBec2']), null, null, 'AUTO', 1,
                      function() {}, undefined, false);


              animateParam(0.25, 1, 2, 'Linear', 'InOut', 0, false,
                  function() {
                setMaterialValue('BlancMeca', 'Value', _pGlob.animateParamUpdate);
              },
                  function() {});

                  MenuStep = 5;
              ShowPic5();
              setHTMLElemStyle('visibility', 'visible', 'ActionTap', true);
            });
          }, undefined, false);

              });
      }, undefined, false);

          });
  }, undefined, false);

      }

// Describe this function...
function PerformTilt4() {
  setHTMLElemStyle('visibility', 'hidden', 'ActionTap', true);
  tweenCamera('CameraMechOpen', 'FocusMain', 2, function() {}, 0);
  outline(['ALL_OBJECTS'], 'DISABLE');
  shadeBodyOff();
}

// Describe this function...
function SetPad5() {
  ShowPic5();
  setHTMLElemStyle('visibility', 'visible', 'ActionTap', true);
  tweenCamera('CameraMechOpen', 'FocusMain', 2, function() {}, 0);
  setHTMLElemStyle('visibility', 'hidden', ['Boutonspares', 'Boutonsparesout'], true);
  setMaterialValue('BlancMeca', 'Value', 1);
  setMaterialValue('BluePaintCarosse', 'Value', 1);
  changeVis(['ALL_OBJECTS'], true);
  outline(['ALL_OBJECTS'], 'DISABLE');
  outline(['GROUP', 'ArrowBec2'], 'ENABLE');
  outline('becquille', 'ENABLE');

  operateAnimation('SET_FRAME', getAnimations(['GROUP', 'CapotAR']), 80, null, 'AUTO', 1,
          function() {}, undefined, false);


  operateAnimation('SET_FRAME', getAnimations(['GROUP', 'FlapAction']), 310, null, 'AUTO', 1,
          function() {}, undefined, false);

      MenuStep = 5;
}

// Describe this function...
function PerformPad5() {
  setHTMLElemStyle('visibility', 'hidden', 'ActionTap', true);

  operateAnimation('PLAY', getAnimations(['GROUP', 'CapotAR']), 0, 80, 'LoopOnce', 1,
          function() {
    outline(['ALL_OBJECTS'], 'DISABLE');
    ArriereOuvert = false;
  }, undefined, true);

      }

// Describe this function...
function ShowPic1() {
  setHTMLElemStyle('left', '0px', 'verticalmap', true);
  setHTMLElemStyle('visibility', 'visible', 'ShadowpicB1', true);
  setHTMLElemStyle('visibility', 'hidden', ['ShadowpicB2', 'ShadowpicB3', 'ShadowpicB4', 'ShadowpicB5', 'ShadowpicB6', 'ShadowpicB7', 'ShadowpicB8', 'ShadowpicB9', 'ShadowpicB10', 'ShadowpicB11', 'ShadowpicB12', 'ShadowpicB13', 'ShadowpicB14', 'ShadowpicB15'], true);
  setHTMLElemStyle('visibility', 'hidden', ['Shadowpic2', 'Shadowpic3', 'Shadowpic4', 'Shadowpic5', 'Shadowpic6', 'Shadowpic7', 'Shadowpic8', 'Shadowpic9', 'Shadowpic10', 'Shadowpic11', 'Shadowpic12', 'Shadowpic13', 'Shadowpic14', 'Shadowpic15'], true);
}

// Describe this function...
function Terminate() {
  setHTMLElemStyle('left', '-250px', 'container_content', true);
  setHTMLElemStyle('left', '0px', 'main', true);
  setHTMLElemStyle('visibility', 'hidden', 'Title3', true);
  setHTMLElemStyle('visibility', 'hidden', 'Title1', true);
  setHTMLElemStyle('visibility', 'hidden', 'Title2', true);
  setHTMLElemStyle('visibility', 'visible', 'Title0', true);
  setHTMLElemStyle('top', '0px', 'verticalmap', true);
  setHTMLElemStyle('left', '210px', 'verticalmap', true);
}

// Describe this function...
function ShowPic2() {
  setHTMLElemStyle('left', '-210px', 'verticalmap', true);
  setHTMLElemStyle('visibility', 'visible', 'ShadowpicB2', true);
  setHTMLElemStyle('visibility', 'hidden', ['ShadowpicB1', 'ShadowpicB3', 'ShadowpicB4', 'ShadowpicB5', 'ShadowpicB6', 'ShadowpicB7', 'ShadowpicB8', 'ShadowpicB9', 'ShadowpicB10', 'ShadowpicB11', 'ShadowpicB12', 'ShadowpicB13', 'ShadowpicB14', 'ShadowpicB15'], true);
  setHTMLElemStyle('visibility', 'hidden', ['Shadowpic1', 'Shadowpic3', 'Shadowpic4', 'Shadowpic5', 'Shadowpic6', 'Shadowpic7', 'Shadowpic8', 'Shadowpic9', 'Shadowpic10', 'Shadowpic11', 'Shadowpic12', 'Shadowpic13', 'Shadowpic14', 'Shadowpic15'], true);
}

// Describe this function...
function ShowPic3() {
  setHTMLElemStyle('left', '-420px', 'verticalmap', true);
  setHTMLElemStyle('visibility', 'visible', 'ShadowpicB3', true);
  setHTMLElemStyle('visibility', 'hidden', ['ShadowpicB2', 'ShadowpicB1', 'ShadowpicB4', 'ShadowpicB5', 'ShadowpicB6', 'ShadowpicB7', 'ShadowpicB8', 'ShadowpicB9', 'ShadowpicB10', 'ShadowpicB11', 'ShadowpicB12', 'ShadowpicB13', 'ShadowpicB14', 'ShadowpicB15'], true);
  setHTMLElemStyle('visibility', 'hidden', ['Shadowpic2', 'Shadowpic1', 'Shadowpic4', 'Shadowpic5', 'Shadowpic6', 'Shadowpic7', 'Shadowpic8', 'Shadowpic9', 'Shadowpic10', 'Shadowpic11', 'Shadowpic12', 'Shadowpic13', 'Shadowpic14', 'Shadowpic15'], true);
}

// Describe this function...
function ShowPic4() {
  setHTMLElemStyle('left', '-630px', 'verticalmap', true);
  setHTMLElemStyle('visibility', 'visible', 'ShadowpicB4', true);
  setHTMLElemStyle('visibility', 'hidden', ['ShadowpicB2', 'ShadowpicB1', 'ShadowpicB3', 'ShadowpicB5', 'ShadowpicB6', 'ShadowpicB7', 'ShadowpicB8', 'ShadowpicB9', 'ShadowpicB10', 'ShadowpicB11', 'ShadowpicB12', 'ShadowpicB13', 'ShadowpicB14', 'ShadowpicB15'], true);
  setHTMLElemStyle('visibility', 'hidden', ['Shadowpic2', 'Shadowpic1', 'Shadowpic3', 'Shadowpic5', 'Shadowpic6', 'Shadowpic7', 'Shadowpic8', 'Shadowpic9', 'Shadowpic10', 'Shadowpic11', 'Shadowpic12', 'Shadowpic13', 'Shadowpic14', 'Shadowpic15'], true);
}

// Describe this function...
function ShowPic5() {
  setHTMLElemStyle('left', '-840px', 'verticalmap', true);
  setHTMLElemStyle('visibility', 'visible', 'ShadowpicB5', true);
  setHTMLElemStyle('visibility', 'hidden', ['ShadowpicB2', 'ShadowpicB1', 'ShadowpicB3', 'ShadowpicB4', 'ShadowpicB6', 'ShadowpicB7', 'ShadowpicB8', 'ShadowpicB9', 'ShadowpicB10', 'ShadowpicB11', 'ShadowpicB12', 'ShadowpicB13', 'ShadowpicB14', 'ShadowpicB15'], true);
  setHTMLElemStyle('visibility', 'hidden', ['Shadowpic2', 'Shadowpic1', 'Shadowpic3', 'Shadowpic4', 'Shadowpic6', 'Shadowpic7', 'Shadowpic8', 'Shadowpic9', 'Shadowpic10', 'Shadowpic11', 'Shadowpic12', 'Shadowpic13', 'Shadowpic14', 'Shadowpic15'], true);
}

// Describe this function...
function ShowPic6() {
  setHTMLElemStyle('left', '-1050px', 'verticalmap', true);
  setHTMLElemStyle('visibility', 'visible', 'ShadowpicB6', true);
  setHTMLElemStyle('visibility', 'hidden', ['ShadowpicB2', 'ShadowpicB1', 'ShadowpicB3', 'ShadowpicB4', 'ShadowpicB5', 'ShadowpicB7', 'ShadowpicB8', 'ShadowpicB9', 'ShadowpicB10', 'ShadowpicB11', 'ShadowpicB12', 'ShadowpicB13', 'ShadowpicB14', 'ShadowpicB15'], true);
  setHTMLElemStyle('visibility', 'hidden', ['Shadowpic2', 'Shadowpic1', 'Shadowpic3', 'Shadowpic4', 'Shadowpic5', 'Shadowpic7', 'Shadowpic8', 'Shadowpic9', 'Shadowpic10', 'Shadowpic11', 'Shadowpic12', 'Shadowpic13', 'Shadowpic14', 'Shadowpic15'], true);
}

// Describe this function...
function ShowPic7() {
  setHTMLElemStyle('left', '-1260px', 'verticalmap', true);
  setHTMLElemStyle('visibility', 'visible', 'ShadowpicB7', true);
  setHTMLElemStyle('visibility', 'hidden', ['ShadowpicB2', 'ShadowpicB1', 'ShadowpicB3', 'ShadowpicB4', 'ShadowpicB5', 'ShadowpicB6', 'ShadowpicB8', 'ShadowpicB9', 'ShadowpicB10', 'ShadowpicB11', 'ShadowpicB12', 'ShadowpicB13', 'ShadowpicB14', 'ShadowpicB15'], true);
  setHTMLElemStyle('visibility', 'hidden', ['Shadowpic2', 'Shadowpic1', 'Shadowpic3', 'Shadowpic4', 'Shadowpic5', 'Shadowpic6', 'Shadowpic8', 'Shadowpic9', 'Shadowpic10', 'Shadowpic11', 'Shadowpic12', 'Shadowpic13', 'Shadowpic14', 'Shadowpic15'], true);
}


'Etats initiaux';

operateAnimation('SET_FRAME', getAnimations(['ALL_OBJECTS']), 0, null, 'AUTO', 1,
        function() {}, undefined, false);

    Unmounted = false;
CarossTranspa = false;
ArriereOuvert = false;
MenuBase = 0;
MenuStep = 0;
outline(['ALL_OBJECTS'], 'DISABLE');
bloom(1.2, 0.2, 1.5);
registerSetTimeout(1, function() {
  tweenCamera('CameraMechOpen', 'FocusMain', 2, function() {}, 0);
});

'Intro';
eventHTMLElem('click', 'tap_0', true, function(event) {
  Reboot();
});
eventHTMLElem('touchstart', 'tap_0', true, function(event) {
  Reboot();
});
eventHTMLElem('click', 'retap_0', true, function(event) {
  Reboot();
});
eventHTMLElem('touchstart', 'retap_0', true, function(event) {
  Reboot();
});

'Selecteursynchro outline';
eventHTMLElem('pointerover', 'tap_One', true, function(event) {
  outline(['GROUP', 'FlapHighlight'], 'ENABLE');
});
eventHTMLElem('pointerout', 'tap_One', true, function(event) {
  outline(['GROUP', 'FlapHighlight'], 'DISABLE');
});
eventHTMLElem('pointerover', 'tap_two', true, function(event) {
  outline(['GROUP', 'TiltMachine'], 'ENABLE');
});
eventHTMLElem('pointerout', 'tap_two', true, function(event) {
  outline(['GROUP', 'TiltMachine'], 'DISABLE');
});
eventHTMLElem('pointerover', 'tap_Three', true, function(event) {
  outline(['GROUP', 'BoltMachine'], 'ENABLE');
});
eventHTMLElem('pointerout', 'tap_Three', true, function(event) {
  outline(['GROUP', 'BoltMachine'], 'DISABLE');
});

'clicmenu';
eventHTMLElem('click', 'tap_One', true, function(event) {
  MenuBase = 1;
  Setpad1();
  setHTMLElemStyle('top', '0px', 'verticalmap', true);
  setHTMLElemStyle('visibility', 'visible', ['picocon1', 'picocon2', 'picocon3', 'picocon4', 'picocon5'], true);
  setHTMLElemStyle('visibility', 'Visible', 'ActionTap', true);
  setHTMLElemStyle('visibility', 'Visible', 'Title1', true);
  setHTMLElemStyle('visibility', 'hidden', 'Title2', true);
  setHTMLElemStyle('visibility', 'hidden', 'Title0', true);
  setHTMLElemStyle('visibility', 'hidden', 'Title3', true);
});
eventHTMLElem('click', 'tap_two', true, function(event) {
  MenuBase = 2;
  SetTilt1();
  setHTMLElemStyle('top', '-250px', 'verticalmap', true);
  setHTMLElemStyle('visibility', 'visible', ['picocon1', 'picocon2', 'picocon3', 'picocon4'], true);
  setHTMLElemStyle('visibility', 'Visible', 'ActionTap', true);
  setHTMLElemStyle('visibility', 'Visible', 'Title2', true);
  setHTMLElemStyle('visibility', 'hidden', 'Title0', true);
  setHTMLElemStyle('visibility', 'hidden', 'Title1', true);
  setHTMLElemStyle('visibility', 'hidden', 'Title3', true);
});
eventHTMLElem('click', 'tap_Three', true, function(event) {
  MenuBase = 3;
  SetMount1();
  setHTMLElemStyle('top', '-500px', 'verticalmap', true);
  setHTMLElemStyle('visibility', 'visible', ['picocon1', 'picocon2', 'picocon3'], true);
  setHTMLElemStyle('visibility', 'Visible', 'ActionTap', true);
  setHTMLElemStyle('visibility', 'Visible', 'Title3', true);
  setHTMLElemStyle('visibility', 'hidden', 'Title1', true);
  setHTMLElemStyle('visibility', 'hidden', 'Title0', true);
  setHTMLElemStyle('visibility', 'hidden', 'Title2', true);
});

'clicmenu';
eventHTMLElem('click', 'tap_exitcontent', true, function(event) {
  Reboot();
  setHTMLElemStyle('visibility', 'hidden', ['picocon1', 'picocon2', 'picocon3', 'picocon4', 'picocon5', 'picocon6', 'picocon7', 'picocon8', 'picocon9', 'picocon10', 'picocon11', 'picocon12', 'picocon13', 'picocon14', 'picocon15'], true);
  setHTMLElemStyle('visibility', 'visible', 'Title0', true);
  setHTMLElemStyle('visibility', 'hidden', ['Title1', 'Title2', 'Title3'], true);
  setHTMLElemStyle('top', '0px', 'verticalmap', true);
});

'Touchstartmenu';
eventHTMLElem('click', 'tap_exitcontent', true, function(event) {
  Reboot();
  setHTMLElemStyle('visibility', 'hidden', ['picocon1', 'picocon2', 'picocon3', 'picocon4', 'picocon5', 'picocon6', 'picocon7', 'picocon8', 'picocon9', 'picocon10', 'picocon11', 'picocon12', 'picocon13', 'picocon14', 'picocon15'], true);
  setHTMLElemStyle('visibility', 'visible', 'Title0', true);
  setHTMLElemStyle('visibility', 'hidden', ['Title1', 'Title2', 'Title3'], true);
  setHTMLElemStyle('top', '0px', 'verticalmap', true);
});

'Touchstartmenu';
eventHTMLElem('click', 'tap_One', true, function(event) {
  MenuBase = 1;
  Setpad1();
  setHTMLElemStyle('top', '0px', 'verticalmap', true);
  setHTMLElemStyle('visibility', 'visible', ['picocon1', 'picocon2', 'picocon3', 'picocon4', 'picocon5'], true);
  setHTMLElemStyle('visibility', 'Visible', 'ActionTap', true);
  setHTMLElemStyle('visibility', 'Visible', 'Title1', true);
  setHTMLElemStyle('visibility', 'hidden', 'Title2', true);
  setHTMLElemStyle('visibility', 'hidden', 'Title0', true);
  setHTMLElemStyle('visibility', 'hidden', 'Title3', true);
});
eventHTMLElem('click', 'tap_two', true, function(event) {
  MenuBase = 2;
  SetTilt1();
  setHTMLElemStyle('top', '-250px', 'verticalmap', true);
  setHTMLElemStyle('visibility', 'visible', ['picocon1', 'picocon2', 'picocon3', 'picocon4'], true);
  setHTMLElemStyle('visibility', 'Visible', 'ActionTap', true);
  setHTMLElemStyle('visibility', 'Visible', 'Title2', true);
  setHTMLElemStyle('visibility', 'hidden', 'Title0', true);
  setHTMLElemStyle('visibility', 'hidden', 'Title1', true);
  setHTMLElemStyle('visibility', 'hidden', 'Title3', true);
});
eventHTMLElem('click', 'tap_Three', true, function(event) {
  MenuBase = 3;
  SetMount1();
  setHTMLElemStyle('top', '-500px', 'verticalmap', true);
  setHTMLElemStyle('visibility', 'visible', ['picocon1', 'picocon2', 'picocon3'], true);
  setHTMLElemStyle('visibility', 'Visible', 'ActionTap', true);
  setHTMLElemStyle('visibility', 'Visible', 'Title3', true);
  setHTMLElemStyle('visibility', 'hidden', 'Title1', true);
  setHTMLElemStyle('visibility', 'hidden', 'Title0', true);
  setHTMLElemStyle('visibility', 'hidden', 'Title2', true);
});

eventHTMLElem('click', 'ActionTap', true, function(event) {
  if (MenuBase == 1 && MenuStep == 1) {
    PerformPad1();
  } else if (MenuBase == 1 && MenuStep == 2) {
    PerformPad2();
  } else if (MenuBase == 1 && MenuStep == 3) {
    PerformPad3();
  } else if (MenuBase == 1 && MenuStep == 4) {
    PerformPad4();
  } else if (MenuBase == 1 && MenuStep == 5) {
    PerformPad5();
  }
});

eventHTMLElem('touchstart', 'ActionTap', true, function(event) {
  if (MenuBase == 1 && MenuStep == 1) {
    PerformPad1();
  } else if (MenuBase == 1 && MenuStep == 2) {
    PerformPad2();
  } else if (MenuBase == 1 && MenuStep == 3) {
    PerformPad3();
  } else if (MenuBase == 1 && MenuStep == 4) {
    PerformPad4();
  } else if (MenuBase == 1 && MenuStep == 5) {
    PerformPad5();
  }
});

eventHTMLElem('click', 'ActionTap', true, function(event) {
  if (MenuBase == 2 && MenuStep == 1) {
    PerformTilt1();
  } else if (MenuBase == 2 && MenuStep == 2) {
    PerformTilt2();
  } else if (MenuBase == 2 && MenuStep == 3) {
    PerformTilt3();
  } else if (MenuBase == 2 && MenuStep == 4) {
    PerformTilt4();
  }
});

eventHTMLElem('touchstart', 'ActionTap', true, function(event) {
  if (MenuBase == 2 && MenuStep == 1) {
    PerformTilt1();
  } else if (MenuBase == 2 && MenuStep == 2) {
    PerformTilt2();
  } else if (MenuBase == 2 && MenuStep == 3) {
    PerformTilt3();
  } else if (MenuBase == 2 && MenuStep == 4) {
    PerformTilt4();
  }
});

eventHTMLElem('click', 'ActionTap', true, function(event) {
  if (MenuBase == 3 && MenuStep == 1) {
    PerformMount1();
  } else if (MenuBase == 3 && MenuStep == 2) {
    PerformMount2();
  } else if (MenuBase == 3 && MenuStep == 3) {
    PerformMount3();
  }
});

eventHTMLElem('touchstart', 'ActionTap', true, function(event) {
  if (MenuBase == 3 && MenuStep == 1) {
    PerformMount1();
  } else if (MenuBase == 3 && MenuStep == 2) {
    PerformMount2();
  } else if (MenuBase == 3 && MenuStep == 3) {
    PerformMount3();
  }
});

'1';
eventHTMLElem('click', 'pico1', true, function(event) {
  if (MenuBase == 1) {
    Setpad1();
  } else if (MenuBase == 2) {
    SetTilt1();
  } else if (MenuBase == 3) {
    SetMount1();
  }
});
eventHTMLElem('touchstart', 'pico1', true, function(event) {
  if (MenuBase == 1) {
    Setpad1();
  } else if (MenuBase == 2) {
    SetTilt1();
  } else if (MenuBase == 3) {
    SetMount1();
  }
});

'3';
eventHTMLElem('click', 'pico3', true, function(event) {
  if (MenuBase == 1) {
    SetPad3();
  } else if (MenuBase == 2) {
    SetTilt3();
  } else if (MenuBase == 3) {
    SetMount3();
  }
});
eventHTMLElem('touchstart', 'pico3', true, function(event) {
  if (MenuBase == 1) {
    SetPad3();
  } else if (MenuBase == 2) {
    SetTilt3();
  } else if (MenuBase == 3) {
    SetMount3();
  }
});

'2';
eventHTMLElem('click', 'pico2', true, function(event) {
  if (MenuBase == 1) {
    SetPad2();
  } else if (MenuBase == 2) {
    SetTilt2();
  } else if (MenuBase == 3) {
    SetMount2();
  }
});
eventHTMLElem('touchstart', 'pico2', true, function(event) {
  if (MenuBase == 1) {
    SetPad2();
  } else if (MenuBase == 2) {
    SetTilt2();
  } else if (MenuBase == 3) {
    SetMount2();
  }
});

'4';
eventHTMLElem('click', 'pico4', true, function(event) {
  if (MenuBase == 1) {
    SetPad4();
  } else if (MenuBase == 2) {
    SetTilt4();
  }
});
eventHTMLElem('touchstart', 'pico4', true, function(event) {
  if (MenuBase == 1) {
    SetPad4();
  } else if (MenuBase == 2) {
    SetTilt4();
  }
});

'5';
eventHTMLElem('click', 'pico5', true, function(event) {
  if (MenuBase == 1) {
    SetPad5();
  }
});
eventHTMLElem('touchstart', 'pico5', true, function(event) {
  if (MenuBase == 1) {
    SetPad5();
  }
});



} // end of PL.init function

})(); // end of closure

/* ================================ end of code ============================= */
